CREATE DATABASE WYDEN_DB;
USE WYDEN_DB;

CREATE TABLE EMPRESA (
    ID_EMPRESA INT UNIQUE NOT NULL AUTO_INCREMENT,
    CNPJ BIGINT(14) UNIQUE NOT NULL,
    NOME VARCHAR(192) NOT NULL,
    CAPITAL_SOCIAL DECIMAL(10,2) NOT NULL,
    LOCAL_DA_SEDE VARCHAR(192) NOT NULL,
    CONSTRAINT CNPJ_LENGTH CHECK (CHARACTER_LENGTH(CNPJ) = 14
        OR ISNULL(CNPJ)),
	CONSTRAINT CAPITAL CHECK (CAPITAL_SOCIAL >= 1000),
    CONSTRAINT LENGTHS CHECK (CHARACTER_LENGTH(NOME) >= 2
        AND CHARACTER_LENGTH(LOCAL_DA_SEDE) >= 10),
	PRIMARY KEY (ID_EMPRESA)
);

CREATE TABLE CAMINHAO(
	ID_CAMINHAO INT UNIQUE NOT NULL AUTO_INCREMENT,
	MODELO VARCHAR(192) NOT NULL,
    PLACA VARCHAR(7) UNIQUE NOT NULL,
    ANO_FABRICACAO INT NOT NULL,
    COMBUSTIVEL VARCHAR(20) NOT NULL,
    PROPRIETARIO INT NOT NULL,
    FOREIGN KEY (PROPRIETARIO) REFERENCES EMPRESA(ID_EMPRESA),
    CONSTRAINT LENGTH CHECK (CHARACTER_LENGTH(MODELO)>=4 AND CHARACTER_LENGTH(PLACA)=7),
    CONSTRAINT VALID_YEAR CHECK(ANO_FABRICACAO >= 1940 AND ANO_FABRICACAO <= 2023)
    );

CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INT UNIQUE NOT NULL AUTO_INCREMENT,
    NACIONALIDADE VARCHAR(64) NOT NULL,
    NOME VARCHAR(192) NOT NULL,
    FUNCAO VARCHAR(64) NOT NULL,
    IDADE INT NOT NULL,
    CPF BIGINT(11) UNIQUE NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    FUNCIONARIO_DA_SEDE BOOL NOT NULL,
    NUMERO_DO_CAMINHAO INT,
    EMPREGADOR INT NOT NULL,
    PRIMARY KEY (ID_FUNCIONARIO),
    FOREIGN KEY (NUMERO_DO_CAMINHAO) REFERENCES CAMINHAO(ID_CAMINHAO),
    FOREIGN KEY (EMPREGADOR) REFERENCES EMPRESA(ID_EMPRESA),
    CONSTRAINT WORKING CHECK (FUNCIONARIO_DA_SEDE = FALSE OR ISNULL(NUMERO_DO_CAMINHAO) = FALSE),
    CONSTRAINT VALID_AGE CHECK (IDADE >= 18 AND IDADE <= 120),
    CONSTRAINT VALID_WAGE CHECK (SALARIO >= 1320),
    CONSTRAINT CPF_LENGTH CHECK (CHARACTER_LENGTH(CPF) = 11),
    CONSTRAINT CNPJ_LENGTH CHECK (CHARACTER_LENGTH(EMPREGADOR) = 14),
    CONSTRAINT VALID_SEX CHECK (SEXO = 'M' OR SEXO = 'F'),
    CONSTRAINT LENGTHS CHECK (CHARACTER_LENGTH(NOME) >= 2
        AND CHARACTER_LENGTH(FUNCAO) >= 4 AND CHARACTER_LENGTH(NACIONALIDADE) >= 4)
);
CREATE TABLE CLIENTE (
    ID_CLIENTE INT UNIQUE NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(192) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CPF BIGINT(11) UNIQUE,
    CNPJ BIGINT(14) UNIQUE,
    IDADE INT NOT NULL,
    NACIONALIDADE VARCHAR(64) NOT NULL,
    ITEM_FAVORITO VARCHAR(128),
    ENDERECO VARCHAR(190) NOT NULL,
    FOOD_TRUCK_PREFERIDO INT NOT NULL,
    PRIMARY KEY (ID_CLIENTE),
    FOREIGN KEY (FOOD_TRUCK_PREFERIDO) REFERENCES CAMINHAO(ID_CAMINHAO),
    CONSTRAINT VALID_AGE CHECK (IDADE >= 18 AND IDADE <= 120),
    CONSTRAINT CPF_LENGTH CHECK (CHARACTER_LENGTH(CPF) = 11 OR CPF = NULL),
    CONSTRAINT CNPJ_LENGTH CHECK (CHARACTER_LENGTH(CNPJ) = 14
        OR ISNULL(CNPJ)),
    CONSTRAINT BOTH_NULL CHECK (ISNULL(CPF) = FALSE
        OR ISNULL(CNPJ) = FALSE),
    CONSTRAINT VALID_SEX CHECK (SEXO = 'M' OR SEXO = 'F'),
    CONSTRAINT LENGTHS CHECK (CHARACTER_LENGTH(NOME) >= 2
        AND CHARACTER_LENGTH(NACIONALIDADE) >= 4 AND CHARACTER_LENGTH(ENDERECO) >= 10)
);