DROP DATABASE WYDEN_DB;
CREATE DATABASE WYDEN_DB;
USE WYDEN_DB;

CREATE TABLE EMPRESA (
    ID_EMPRESA INT UNIQUE NOT NULL AUTO_INCREMENT,
    CNPJ BIGINT(14) UNIQUE NOT NULL,
    NOME VARCHAR(192) NOT NULL,
    CAPITAL_SOCIAL DECIMAL(10,2) NOT NULL,
    LOCAL_DA_SEDE VARCHAR(192) NOT NULL,
    CONSTRAINT CNPJ_LENGTH CHECK (CHARACTER_LENGTH(CNPJ) = 14),
	CONSTRAINT CAPITAL CHECK (CAPITAL_SOCIAL >= 1000),
    CONSTRAINT LENGTHS CHECK (CHARACTER_LENGTH(NOME) >= 2
        AND CHARACTER_LENGTH(LOCAL_DA_SEDE) >= 4),
	PRIMARY KEY (ID_EMPRESA)
);

CREATE TABLE CAMINHAO(
	ID_CAMINHAO INT UNIQUE NOT NULL AUTO_INCREMENT,
	MODELO VARCHAR(192) NOT NULL,
    PLACA VARCHAR(7) UNIQUE NOT NULL,
    ANO_FABRICACAO INT NOT NULL,
    COMBUSTIVEL VARCHAR(20) NOT NULL,
    PROPRIETARIO INT NOT NULL,
    PRIMARY KEY (ID_CAMINHAO),
    FOREIGN KEY (PROPRIETARIO) REFERENCES EMPRESA(ID_EMPRESA),
    CONSTRAINT LENGTH CHECK (CHARACTER_LENGTH(MODELO)>=4 AND CHARACTER_LENGTH(PLACA)=7),
    CONSTRAINT VALID_YEAR CHECK(ANO_FABRICACAO >= 1940 AND ANO_FABRICACAO <= 2023)
    );

CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INT UNIQUE NOT NULL AUTO_INCREMENT,
    NACIONALIDADE VARCHAR(64) NOT NULL,
    NOME VARCHAR(192) NOT NULL,
    FUNCAO VARCHAR(64) NOT NULL,
    IDADE INT NOT NULL,
    CPF BIGINT(11) UNIQUE NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    FUNCIONARIO_DA_SEDE BOOL NOT NULL,
    NUMERO_DO_CAMINHAO INT,
    EMPREGADOR INT NOT NULL,
    PRIMARY KEY (ID_FUNCIONARIO),
    FOREIGN KEY (NUMERO_DO_CAMINHAO) REFERENCES CAMINHAO(ID_CAMINHAO),
    FOREIGN KEY (EMPREGADOR) REFERENCES EMPRESA(ID_EMPRESA),
    CONSTRAINT WORKING CHECK (FUNCIONARIO_DA_SEDE = FALSE OR (NUMERO_DO_CAMINHAO) <> NULL),
    CONSTRAINT VALID_AGE CHECK (IDADE >= 18 AND IDADE <= 120),
    CONSTRAINT VALID_WAGE CHECK (SALARIO >= 1320),
    CONSTRAINT CPF_LENGTH CHECK (CHARACTER_LENGTH(CPF) = 11),
    CONSTRAINT VALID_SEX CHECK (SEXO = 'M' OR SEXO = 'F'),
    CONSTRAINT LENGTHS CHECK (CHARACTER_LENGTH(NOME) >= 2
        AND CHARACTER_LENGTH(FUNCAO) >= 4 AND CHARACTER_LENGTH(NACIONALIDADE) >= 4)
);
CREATE TABLE CLIENTE (
    ID_CLIENTE INT UNIQUE NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(192) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CPF BIGINT(11) UNIQUE,
    CNPJ BIGINT(14) UNIQUE,
    IDADE INT NOT NULL,
    NACIONALIDADE VARCHAR(64) NOT NULL,
    ITEM_FAVORITO VARCHAR(128),
    ENDERECO VARCHAR(190) NOT NULL,
    FOOD_TRUCK_PREFERIDO INT NOT NULL,
    PRIMARY KEY (ID_CLIENTE),
    FOREIGN KEY (FOOD_TRUCK_PREFERIDO) REFERENCES CAMINHAO(ID_CAMINHAO),
    CONSTRAINT VALID_AGE CHECK (IDADE >= 18 AND IDADE <= 120),
    CONSTRAINT CPF_LENGTH CHECK (CHARACTER_LENGTH(CPF) = 11 OR CPF = NULL),
    CONSTRAINT CNPJ_LENGTH CHECK (CHARACTER_LENGTH(CNPJ) = 14
        OR ISNULL(CNPJ)),
    CONSTRAINT BOTH_NULL CHECK (ISNULL(CPF) = FALSE
        OR ISNULL(CNPJ) = FALSE),
    CONSTRAINT VALID_SEX CHECK (SEXO = 'M' OR SEXO = 'F'),
    CONSTRAINT LENGTHS CHECK (CHARACTER_LENGTH(NOME) >= 2
        AND CHARACTER_LENGTH(NACIONALIDADE) >= 4 AND CHARACTER_LENGTH(ENDERECO) >= 10)
);

INSERT INTO EMPRESA (CNPJ, NOME,CAPITAL_SOCIAL,LOCAL_DA_SEDE) VALUES (12345678901234, "MCDONALDS", 50000, "SÃO PAULO");
INSERT INTO EMPRESA (CNPJ, NOME,CAPITAL_SOCIAL,LOCAL_DA_SEDE) VALUES (23456789012345, "BURGER KING", 100000, "CURITIBA");
INSERT INTO EMPRESA (CNPJ, NOME,CAPITAL_SOCIAL,LOCAL_DA_SEDE) VALUES (34567890123456, "KFC", 500000, "SÃO PAULO");

INSERT INTO CAMINHAO (MODELO,PLACA,ANO_FABRICACAO,COMBUSTIVEL,PROPRIETARIO) VALUES ("FIAT DUCATO","ABC1234",2011,"DIESEL",3);
INSERT INTO CAMINHAO (MODELO,PLACA,ANO_FABRICACAO,COMBUSTIVEL,PROPRIETARIO) VALUES ("FIAT DUCATO","ABC2345",2012,"DIESEL",3);
INSERT INTO CAMINHAO (MODELO,PLACA,ANO_FABRICACAO,COMBUSTIVEL,PROPRIETARIO) VALUES ("FIAT DUCATO","ABC3456",2009,"DIESEL",2);
INSERT INTO CAMINHAO (MODELO,PLACA,ANO_FABRICACAO,COMBUSTIVEL,PROPRIETARIO) VALUES ("CITROEN JUMPER","ABC4567",2010,"DIESEL",2);
INSERT INTO CAMINHAO (MODELO,PLACA,ANO_FABRICACAO,COMBUSTIVEL,PROPRIETARIO) VALUES ("CITROEN JUMPER","ABC0123",2011,"DIESEL",1);
INSERT INTO CAMINHAO (MODELO,PLACA,ANO_FABRICACAO,COMBUSTIVEL,PROPRIETARIO) VALUES ("RENAUL MASTER","ABC5678",2013,"DIESEL",1);

INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "BRUNO", "COZINHEIRO", 32,"M", 12345678901, 2500, FALSE,3,1);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "ROBERTO", "MOTORISTA", 26,"M", 23456789012, 2000, FALSE,3,1);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "JOSÉ", "MOTORISTA", 34,"M", 34567890123, 2000, FALSE,3,2);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "JOÃO", "COZINHEIRO", 24,"M", 45678901234, 2500, FALSE,3,2);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "ANTONIO", "CONTADOR", 40,"M", 56789012345, 4500, TRUE,3,NULL);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "RODRIGO", "FAXINEIRO", 30,"M", 67890123456, 1400, TRUE,3,NULL);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("PORTUGUESA", "MARIA", "PROPRIETARIA", 25,"F", 78901234567, 7500, TRUE,3,NULL);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO)VALUES ("BRASILEIRO", "EDUARDO", "MECANICO", 42,"M", 89102345678, 3000, TRUE,3,NULL);

INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("AMERICANO", "JACK", "COZINHEIRO", 32,"M", 98765432109, 2200, FALSE,2,3);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "LUIS", "MOTORISTA", 26,"M", 87654321098, 1800, FALSE,2,3);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("CHINES", "HUANG", "MOTORISTA", 34,"M", 76543210987, 1800, FALSE,2,4);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "EDSON", "COZINHEIRO", 24,"M", 65432109876, 2200, FALSE,2,4);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("COLOMBIANO", "ANTONIO", "CONTADOR", 40,"M", 54321098765, 4000, TRUE,2,NULL);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "RODRIGO", "FAXINEIRO", 30,"M", 43210987654, 1400, TRUE,2,NULL);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "EMERSON", "PROPRIETARIO", 32,"M", 32109876543, 6500, TRUE,2,NULL);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "EDUARDO", "MECANICO", 42,"M", 21098765432, 2800, TRUE,2,NULL);

INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("ITALIANO", "CLAUDIO", "COZINHEIRO", 32,"M", 98765432101, 2200, FALSE,1,5);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "LUIS", "MOTORISTA", 26,"M", 87654321012, 1800, FALSE,1,5);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("AMERICANO", "HANK", "MOTORISTA", 40,"M",  76543210234, 1800, FALSE,1,6);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("AMERICANO", "WALTER", "COZINHEIRO", 50,"M", 65432102345, 2200, FALSE,1,6);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("COLOMBIANO", "PABLO", "CONTADOR", 32,"M", 54321012345, 4000, TRUE,1,NULL);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "RODRIGO", "FAXINEIRO", 30,"M", 43210123456, 1400, TRUE,1,NULL);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("AMERICANO", "GUS", "PROPRIETARIO", 32,"M", 32101234567, 6500, TRUE,1,NULL);
INSERT INTO FUNCIONARIOS (NACIONALIDADE,NOME,FUNCAO,IDADE,SEXO,CPF,SALARIO,FUNCIONARIO_DA_SEDE,EMPREGADOR,NUMERO_DO_CAMINHAO) VALUES ("BRASILEIRO", "EDUARDO", "MECANICO", 42,"M", 21012345678, 2800, TRUE,1,NULL);

INSERT INTO CLIENTE(NOME,SEXO,CPF,CNPJ,IDADE,NACIONALIDADE,ITEM_FAVORITO,ENDERECO,FOOD_TRUCK_PREFERIDO) VALUES("VINCENT","M",98778965445,NULL, 35, "AMERICANO","LE BIG MAC","RUA LTD1 - SÃO PAULO",6);
INSERT INTO CLIENTE(NOME,SEXO,CPF,CNPJ,IDADE,NACIONALIDADE,ITEM_FAVORITO,ENDERECO,FOOD_TRUCK_PREFERIDO) VALUES("JULES","M",87898765456,NULL, 38, "AMERICANO","BIG KAHUNA","RUA LTD2 - SÃO PAULO",5);
INSERT INTO CLIENTE(NOME,SEXO,CPF,CNPJ,IDADE,NACIONALIDADE,ITEM_FAVORITO,ENDERECO,FOOD_TRUCK_PREFERIDO) VALUES("MAX","M",78998765445,NULL, 25, "BRASILEIRO","WHOPPER","RUA ESP1 - CURITIBA",4);
INSERT INTO CLIENTE(NOME,SEXO,CPF,CNPJ,IDADE,NACIONALIDADE,ITEM_FAVORITO,ENDERECO,FOOD_TRUCK_PREFERIDO) VALUES("KIKO","M",6544563212,NULL, 23, "BRASILEIRO","MASTER SHAKE","RUA ESP2 - CURITIBA",3);
INSERT INTO CLIENTE(NOME,SEXO,CPF,CNPJ,IDADE,NACIONALIDADE,ITEM_FAVORITO,ENDERECO,FOOD_TRUCK_PREFERIDO) VALUES("ROGER","M",54565432112,NULL, 40, "BRASILEIRO","FRYLOCK","RUA SOLAR 1 - SP",2);
INSERT INTO CLIENTE(NOME,SEXO,CPF,CNPJ,IDADE,NACIONALIDADE,ITEM_FAVORITO,ENDERECO,FOOD_TRUCK_PREFERIDO) VALUES("VITO","M",45665432112,NULL, 50, "ITALIANO","RED SPECIAL","RUA SOLAR2 - SÃO PAULO",1);